# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 837376d1bd5d9e2fe05e02aa07dbeea800d252da163c054b06a90604fec4c747fa25810c926829a12b479627e83570b71724deda98291e6e503ddc05913e344b

test:
  secret_key_base: c116e8edeafa1bf372f381e0958efb89b450e2dcb13b79f297bcbb24abc8d3c3956e29e469aaa89128e32c62f595e6d021b2ca69fd98d9528c5f42de7f6728a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
